const timezones = [
    { name: 'London', timezone: 'Europe/London', utcOffset: '+00:00' },
    { name: 'Paris', timezone: 'Europe/Paris', utcOffset: '+01:00' },
    { name: 'Tokyo', timezone: 'Asia/Tokyo', utcOffset: '+09:00' },
    { name: 'Sydney', timezone: 'Australia/Sydney', utcOffset: '+10:00' },
    { name: 'New York', timezone: 'America/New_York', utcOffset: '-05:00' },
    { name: 'Los Angeles', timezone: 'America/Los_Angeles', utcOffset: '-08:00' },
    { name: 'Dubai', timezone: 'Asia/Dubai', utcOffset: '+04:00' },
    { name: 'Bangkok', timezone: 'Asia/Bangkok', utcOffset: '+07:00' },
    { name: 'Singapore', timezone: 'Asia/Singapore', utcOffset: '+08:00' },
    { name: 'Hong Kong', timezone: 'Asia/Hong_Kong', utcOffset: '+08:00' },
    { name: 'Mumbai', timezone: 'Asia/Kolkata', utcOffset: '+05:30' },
    { name: 'Istanbul', timezone: 'Europe/Istanbul', utcOffset: '+03:00' },
    { name: 'Moscow', timezone: 'Europe/Moscow', utcOffset: '+03:00' },
    { name: 'Sao Paulo', timezone: 'America/Sao_Paulo', utcOffset: '-03:00' },
    { name: 'Mexico City', timezone: 'America/Mexico_City', utcOffset: '-06:00' },
    { name: 'Toronto', timezone: 'America/Toronto', utcOffset: '-05:00' },
    { name: 'Vancouver', timezone: 'America/Vancouver', utcOffset: '-08:00' },
    { name: 'Auckland', timezone: 'Pacific/Auckland', utcOffset: '+12:00' },
    { name: 'Honolulu', timezone: 'Pacific/Honolulu', utcOffset: '-10:00' },
    { name: 'Berlin', timezone: 'Europe/Berlin', utcOffset: '+01:00' },
    { name: 'Madrid', timezone: 'Europe/Madrid', utcOffset: '+01:00' },
    { name: 'Rome', timezone: 'Europe/Rome', utcOffset: '+01:00' },
    { name: 'Amsterdam', timezone: 'Europe/Amsterdam', utcOffset: '+01:00' },
    { name: 'Seoul', timezone: 'Asia/Seoul', utcOffset: '+09:00' },
    { name: 'Manila', timezone: 'Asia/Manila', utcOffset: '+08:00' },
    { name: 'Jakarta', timezone: 'Asia/Jakarta', utcOffset: '+07:00' }
];